version: "3"
services:

  ############# External services

  memcached:
    image: memcached:1.4.38
    restart: unless-stopped

  mongodb:
    image: mongo:3.0.14
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db

  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    #env_file: ./config/mysql/auth.env

  rabbitmq:
    image: rabbitmq:3.6.10
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  ############# LMS and CMS
#
#  lms:
#    image: regis/openedx:ginkgo
#    build:
#      context: ./openedx
#    environment:
#      SERVICE_VARIANT: lms
#    restart: unless-stopped
#    volumes:
#      - ./config/openedx:/openedx/config
#      - ./data/lms:/openedx/data
#    depends_on:
#      - memcached
#      - mongodb
#      - mysql
#      - rabbitmq
      
